# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
          password: ${{ secrets.SSH_PASSWORD }} # Password of the server you want to ssh into
          
          script: |
            mkdir -p apps
            cd apps
            npx kill-port 8000
            rm -rf Mediasoup-Server
            git clone git@github.com:z3r0c00l-2k/Mediasoup-Server.git
            cd Mediasoup-Server
            yarn
            yarn start
            echo 'Deployment successful to digital ocean' 